### ISSUE TITLE
Differentiate PathParameter from QueryParameter

### ISSUE THREAD

**Issue by Hazer** [alexfacciorusso/urc#1]
Hi,

I suggest you to differentiate Parameters for Path construction, from Parameters for Query.
Given example:

```
/users/:username?username=Lala
```

I know you can change :username to something else (:_username) and that the above example its not that common. I think its safer, if you can see your mistakes easily.

I would suggest:

```
myApi.fromEndpoint(...)
  .setPathParam("username", "default") // Can be used defaults this way, so its easy to reuse
  .setPathParam("username", "lala")
  .addQueryParam("username", "someuser")
```

else:

```
myApi.fromEndpoint(...)
  .setParameter("username", "default") // Can be used defaults this way, so its easy to reuse
  .setParameter("username", "lala")
  .queryParams() // Remove the need for setQueryParametersEnabled/1
  .addParameter("username", "someuser")
```

I would like to know what do you think.

Thanks!

**Comment by alexfacciorusso** [comment]
I will take inspiration from this suggestion.
I will add in next release an `ignoreUnmatchedParameters()`method into builder to substitute the old `setQueryParametersEnabled()`, and i will add two new methods (and overloads): `addQueryParameter`and `addPathParameter`. These methods are used to insert "manual parameters", that will be only used for query and path. If a path parameter is unmatched, that parameter will be always ignored. The auto parameters (the ones added by addParameter) will be overwritten by explicit query and path parameters with same key, if existent.
